# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mv6Nz1KxAZeMrvpsieh3cGTJKnhW_kqo
"""

pip install requests

import requests

from datetime import datetime

api_key ='af0289272579ddd49e4c63033d5149d5'

location = input("Enter the city name: ")

complete_api_link =  "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key

api_link = requests.get(complete_api_link)

api_data = api_link.json()

temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

import logging

logger = logging.getLogger('my_loggerfile')

logging.basicConfig(level=logging.DEBUG)

logging.info("hi")

logger.error("hello")

from pathlib import Path

# Commented out IPython magic to ensure Python compatibility.
# %%python
# 
# import logging
# logger = logging.getLogger('my_logger')
# 
# logging.basicConfig(
#     filename='app.log', # write to this file
#     filemode='a', # open in append mode
#     format='%(name)s - %(levelname)s - %(message)s'
#     )
# 
# logging.warning('This will get logged to a file')

print(Path('app.log').read_text())

import logging
logging.basicConfig(format='%(asctime)s - %(message)s', level=logging.INFO)
logger.info('This message has a date/time timestamp')

temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

logging.error(f'{location}')
logging.info(f'the current temperature is {temp_city}')
logging.info(f'the current description is {weather_desc}')
logging.info(f'the current humidity level is {hmdt}')
logging.info(f'the current wind speed  is {wind_spd}')

